# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#    https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/
# Happy Coding!

service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  memorySize: 128
  # apiKeys:
  #   - myAPIKey
  # usagePlan:
  #   quota:
  #     limit: 500
  #     offset: 0
  #     period: DAY
  #   throttle:
  #     burstLimit: 10
  #     rateLimit: 10

# The `functions` block defines what code to deploy
functions:
  football-get:
    handler: handler.main
    timeout: 15
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: results
          method: get
          cors: true
          # private: true
